### PR TITLE
Show smallest factor of a number n (except 1)

### PR DESCRIPTION
**Pull request by abhishekb13402**

### CODE REVIEW

**Review by SonuKumar81800 — CHANGES_REQUESTED** [review]
@abhishekb13402 please work on any algorithm and then create pull request

**Review by SonuKumar81800 — CHANGES_REQUESTED** [review]
Please do not create pull request just for hacktoberfest task. 

work on some advance algorithm.

**Comment by recurrenc** [comment]
Not getting any response from @abhishekb13402

**Comment by abhishekb13402** [comment]
no sir i work on project please not make me spam

**Comment by SonuKumar81800** [comment]
ok @abhishekb13402 work on it

**Review by SonuKumar81800 — APPROVED** [review]

**Comment by abhishekb13402** [comment]
thank you so much sir

**Pull request merged**
